steps:
  # Docker Build
  # replace using project name or id after gcr.io/
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      [
        "build",
        "-t",
        "gcr.io/zeta-crossbar-371709/github.com/ramadlana/rama-reactjs-starterkit:$SHORT_SHA",
        ".",
      ]
  # Push Image to registry
  # gcr.io/project-name-or-id/github.com/ramadlana/rama-reactjs-starterkit:$SHORT_SHA
  - name: "gcr.io/cloud-builders/docker"
    id: "push"
    waitFor: ["build"]
    args:
      [
        "push",
        "gcr.io/zeta-crossbar-371709/github.com/ramadlana/rama-reactjs-starterkit:$SHORT_SHA",
      ]
  # Deploy to cloudrun
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy"
    waitFor: ["push"]
    args:
      [
        "run",
        "deploy",
        "reactstarterkit",
        "--port=3000",
        "--image=gcr.io/zeta-crossbar-371709/github.com/ramadlana/rama-reactjs-starterkit:$SHORT_SHA",
        "--allow-unauthenticated",
        "--region=asia-southeast2-a",
        "--max-instances=1",
        "--project=zeta-crossbar-371709",
      ]
  # Update traffic
  - name: "gcr.io/cloud-builders/gcloud"
    id: "update-traffic"
    waitFor: ["deploy"]
    args:
      [
        "run",
        "services",
        "update-traffic",
        "react-starter-kit-vite",
        "--to-latest",
        "--region=asia-southeast2-a",
      ]
